### ISSUE TITLE
교수님께 질문할 것들

### ISSUE THREAD

**Issue by YuYoungGyu** [ADSL-SSU/r-real-estate-price#3]
나의 힘으로 해결이 되지 않는 것들은 여기에 정리

**Comment by YuYoungGyu** [comment]
1. 기사를 crawling한 csv파일에 저장된 url과 pandas로 read한 url이 다르다.
csv파일에 저장된 ur = https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=260&oid=023&aid=0003580242
pandas로 read한 url = https://news.naver.com/main/read.nhn?mode=LSD&amp;mid=shm&amp;sid1=260&amp;oid=023&amp;aid=0003580242

@bluekura

**Comment by bluekura** [comment]
@YuYoungGyu 
https://www.web2generators.com/html-based-tools/online-html-entities-encoder-and-decoder

url encode-decode때문에 그렇습니다. 위 사이트에서 아래 주소 넣고 decode를 하시면 위의 주소가 나옵니다.
아래의 두가지를 체크해보세요.

https://medium.com/@dhiraj.sanju/decode-urls-using-pandas-and-urllib-in-python-3ef355a78826
https://pydole.tistory.com/entry/Python-padnas-dataframe-URL-Decode

**Comment by YuYoungGyu** [comment]
@bluekura 
```
from urllib.parse import unquote
import pandas as pd

path = '../output/'

df = pd.read_csv(f'{path}Article_부동산_200601_200601.csv', names = ['date','co','haedline','text','url'],encoding = 'cp949')

print('encode url')
print(df['url'][0])

df['url'] = df.url.apply(lambda x : unquote(x))

print('decode url')
print(df['url'][0])
```
위 코드로 실행하였는데 아래와 같이 나왔습니다.(변화 없음)
```
encode url
https://news.naver.com/main/read.nhn?mode=LSD&amp;mid=shm&amp;sid1=260&amp;oid=009&amp;aid=0000479683
decode url
https://news.naver.com/main/read.nhn?mode=LSD&amp;mid=shm&amp;sid1=260&amp;oid=009&amp;aid=0000479683
​
````
혹시 파일 read를 위해 적은 encoding = 'cp949'이 문제 인가요?
파일을 read할때 encoding = 'cp949'을 추가하지 않으면 열리지 않아서요...

크롤링에 사용한 ArticleCrawler 코드에서 url이 어떻게 저장되었는지 확인하고 다시 말씀 드리겠습니다.

**Comment by bluekura** [comment]
https://docs.python.org/3/library/html.html#html.unescape

 이거 시도해보실래요?

2021년 2월 5일 (금) 오후 5:55, YuYoungGyu <notifications@github.com>님이 작성:

**Comment by YuYoungGyu** [comment]
@bluekura 
```
import pandas as pd
import html

path = '../output/'

column_name = ['date','co','headline','text','url']

article = pd.read_csv(f'{path}Article_부동산_200601_200601.csv', names = column_name, encoding = 'CP949')

print('before:', end = ' ')
print(article['url'][0])

print('after:', end = ' ')
print(html.unescape(article['url'][0]))
```
```
before: https://news.naver.com/main/read.nhn?mode=LSD&amp;mid=shm&amp;sid1=260&amp;oid=009&amp;aid=0000479683
after: https://news.naver.com/main/read.nhn?mode=LSD&amp;mid=shm&amp;sid1=260&amp;oid=009&amp;aid=0000479683
```
바뀌지 않습니다...

혹시 몰라 crawler 코드에서 url 저장 방법 확인해보았는데
`post_urls.append(line.a.get('href'))`
딱히 이상한건 없어보였습니다

또한 escape 코드도 보았는데
```
def escape(s, quote=True):
    s = s.replace("&", "&amp;") # Must be done first!
    s = s.replace("<", "&lt;")
    s = s.replace(">", "&gt;")
    if quote:
        s = s.replace('"', "&quot;")
        s = s.replace('\'', "&#x27;")
    return s
```
문제가 되는 url과 encode 방식이 같은것 같은데 왜 unescape가 안되는지 모르겠습니다...

**Comment by YuYoungGyu** [comment]
문제가 되는 url 중간에 섞인 "amp;"만 없애면 정상적인 url이라 제거를 시도해보았는데
```
def url_decode(url):
    url = url.replace("amp;","")
    return url
        
url = 'https://news.naver.com/main/read.nhn?mode=LSD&amp;mid=shm&amp;sid1=260&amp;oid=009&amp;aid=0000479683'
url = url_decode(url)
print(url)
```
`https://news.naver.com/main/read.nhn?mode=LSD&amp;mid=shm&amp;sid1=260&amp;oid=009&amp;aid=0000479683`
되지 않았습니다.

**Comment by bluekura** [comment]
```python
url_decode(url.decode("cp949").encode("utf8"))
```
를 한번 시도해보세요.
이런 형태로 성공한다면
```python
df["something"] = df["something"].str.decode("cp949").encode("utf8")
```
형태로 전체를 unicode로 바꾸고 다시 시도해보시면 어떨까요
python 3의 기본 encoding이 utf8이라서 발생하는 문제같기도 한데...

참고로 utf8인지 utf-8인지 잘 기억이 안나니 두개 다 해보세요 -_-;;; (제가 지금 직접 돌려볼 상황이 아니네요)

**Comment by YuYoungGyu** [comment]
해결했습니다!
바쁘실텐데 감사합니다~
